---
name: Hello Wolrd workflow
on:
  push:
    branches:
      - main: null
  pull_request:
    branches:
      - main: null
  workflow_dispatch: null
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello Wolrd"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye Wolrd"
        shell: bash
